const contractAddress = "0xA20B9c50Dd9b5A963e7af2d57754bB4F22633bd9"; // Replace with your own contract address
const chain = 'polygon'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Bienvenidos al mint de Cool Programmers";
const welcome_h2 = "Conéctate a metamask para empezar";
const welcome_p = 'La colección Cool Programmers es una colección de prueba. En la actualidad no existe ninguna colección solo de programadores y somos la primera. ¿Qué utilidad tiene? Quien sabe... puede que sea solo un PFP o que sea la whitelist directa a...';
const h1_presale_coming_soon = "Próximamente, puede que haya un Airdrop...";
const h1_presale_mint = "Pre-Sale Minting Abierto!!";
const h1_public_mint = "Minting público abierto!!";
const h2_presale_coming_soon = "Cuenta atrás pre-sale minting";
const h2_presale_mint = "Cuenta atrás minting público";
const p_presale_coming_soon = "Se está empezando a cocer algo MUY grande...";
const p_presale_mint_not_whitelisted = "No estás en la whitelist de la pre-sale.. 😢";
const p_presale_mint_whitelisted = "Estás en la whitelist de la pre-sale! 🎉";
const p_presale_mint_already_minted = "Ya has reclamado tu whitelist de la presale. Gracias! 🎉";
const p_public_mint = "No se necesita whitelist. El minting al público ya está listo! 🎉";
const button_presale_coming_soon = "Accede a la whihtelist";
const button_presale_mint_whitelisted = "Mintea tu NFT";
const button_presale_mint_not_whitelisted = "Accede a la Whitelist";
const button_presale_already_minted = "Únete a la comunidad";
const button_public_mint = "Mintea tu NFT";
const mint_failed = "Error en el mint. 😢 Por favor, inténtalo de nuevo.";
